{
    "Service": "/MDK1vMore/Services/service1.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/MDK1vMore/Actions/Service/InitializeOnlineSuccessMessage.action",
    "OnFailure": "/MDK1vMore/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}